FROM node:24-alpine

RUN corepack enable

WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY apps/public/package.json ./apps/public/
COPY packages/database/package.json ./packages/database/
COPY packages/types/package.json ./packages/types/
COPY packages/ui/package.json ./packages/ui/
COPY tooling/typescript/package.json ./tooling/typescript/
COPY tooling/eslint/package.json ./tooling/eslint/
COPY tooling/tailwind/package.json ./tooling/tailwind/

RUN pnpm install --frozen-lockfile

COPY tooling ./tooling

COPY packages/database ./packages/database
RUN pnpm --filter @mpga/database build

COPY packages/types ./packages/types
RUN pnpm --filter @mpga/types build

COPY packages/ui ./packages/ui
RUN pnpm --filter @mpga/ui build

COPY apps/public ./apps/public

WORKDIR /app/apps/public

EXPOSE 4000

CMD ["pnpm", "dev"]
